"""initial schema

Revision ID: 607eae6aadb0
Revises: 
Create Date: 2026-07-19 17:13:31.450934
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '607eae6aadb0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Extensions: pgcrypto -> gen_random_uuid(); pg_trgm -> fast ILIKE/trigram search.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=300), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('publisher', sa.String(length=300), nullable=True),
    sa.Column('published_year', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_index(op.f('ix_books_author'), 'books', ['author'], unique=False)
    op.create_index(op.f('ix_books_category'), 'books', ['category'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_table('members',
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', name='memberstatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_email'), 'members', ['email'], unique=True)
    op.create_table('staff_users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'librarian', name='staffrole', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_users_email'), 'staff_users', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('actor_staff_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_staff_id'], ['staff_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_staff_id'), 'audit_log', ['actor_staff_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('book_copies',
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('condition', sa.Enum('new', 'good', 'worn', 'damaged', name='copycondition', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('available', 'borrowed', 'lost', 'maintenance', name='copystatus', native_enum=False, length=32), nullable=False),
    sa.Column('acquired_on', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_copies_barcode'), 'book_copies', ['barcode'], unique=True)
    op.create_index(op.f('ix_book_copies_book_id'), 'book_copies', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_copies_status'), 'book_copies', ['status'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_staff_id'), 'refresh_tokens', ['staff_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('loans',
    sa.Column('copy_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('borrowed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'returned', 'overdue', name='loanstatus', native_enum=False, length=32), nullable=False),
    sa.Column('renewed_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['copy_id'], ['book_copies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_active_loans_by_member', 'loans', ['member_id'], unique=False, postgresql_where=sa.text('returned_at IS NULL'))
    op.create_index(op.f('ix_loans_copy_id'), 'loans', ['copy_id'], unique=False)
    op.create_index(op.f('ix_loans_member_id'), 'loans', ['member_id'], unique=False)
    op.create_index(op.f('ix_loans_status'), 'loans', ['status'], unique=False)
    op.create_index('uq_active_loan_per_copy', 'loans', ['copy_id'], unique=True, postgresql_where=sa.text('returned_at IS NULL'))
    op.create_table('fines',
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('pending', 'paid', 'waived', name='finestatus', native_enum=False, length=32), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fines_loan_id'), 'fines', ['loan_id'], unique=False)
    op.create_index(op.f('ix_fines_member_id'), 'fines', ['member_id'], unique=False)
    op.create_index(op.f('ix_fines_status'), 'fines', ['status'], unique=False)
    # ### end Alembic commands ###

    # Trigram (GIN) indexes for fast case-insensitive title/author search (F4).
    op.execute(
        "CREATE INDEX ix_books_title_trgm ON books USING gin (title gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_books_author_trgm ON books USING gin (author gin_trgm_ops)"
    )

    # Keep updated_at correct even for raw SQL updates (defense in depth vs the ORM onupdate).
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table in ("books", "members", "staff_users", "book_copies", "loans", "fines"):
        op.execute(
            f"CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
        )


def downgrade() -> None:
    # Triggers drop automatically with their tables; remove the shared function afterwards.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fines_status'), table_name='fines')
    op.drop_index(op.f('ix_fines_member_id'), table_name='fines')
    op.drop_index(op.f('ix_fines_loan_id'), table_name='fines')
    op.drop_table('fines')
    op.drop_index('uq_active_loan_per_copy', table_name='loans', postgresql_where=sa.text('returned_at IS NULL'))
    op.drop_index(op.f('ix_loans_status'), table_name='loans')
    op.drop_index(op.f('ix_loans_member_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_copy_id'), table_name='loans')
    op.drop_index('ix_active_loans_by_member', table_name='loans', postgresql_where=sa.text('returned_at IS NULL'))
    op.drop_table('loans')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_staff_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_book_copies_status'), table_name='book_copies')
    op.drop_index(op.f('ix_book_copies_book_id'), table_name='book_copies')
    op.drop_index(op.f('ix_book_copies_barcode'), table_name='book_copies')
    op.drop_table('book_copies')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_staff_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_staff_users_email'), table_name='staff_users')
    op.drop_table('staff_users')
    op.drop_index(op.f('ix_members_email'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_category'), table_name='books')
    op.drop_index(op.f('ix_books_author'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION IF EXISTS set_updated_at() CASCADE")
